import type { LoanApplication, User, ApplicationDocument, RiskAssessment, LoanDecision, LoanProduct } from '../types';
import { calculateEmi, calculateDti, calculateDisposableIncome } from '../utils/financial';

export interface RawBorrowerData {
  id: string;
  name: string;
  email: string;
  phone: string;
  pan: string;
  city: string;
  address: string;
  employer: string;
  jobTitle: string;
  yearsEmployed: number;
  income: number;
  existingDebt: number;
  housingExpense: number;
  cibil: number;
  productIdx: number; // 0: Personal, 1: Auto, 2: Home
  amount: number;
  tenor: number;
  purpose: string;
  status: LoanApplication['status'];
}

export const INDIAN_BORROWER_PROFILES: RawBorrowerData[] = [
  {
    id: 'ind-001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@gmail.com',
    phone: '+91 98112 34501',
    pan: 'AAAPS1201A',
    city: 'New Delhi, Delhi',
    address: '42 Barakhamba Road, Connaught Place',
    employer: 'Tata Consultancy Services',
    jobTitle: 'Lead Software Architect',
    yearsEmployed: 7.5,
    income: 185000,
    existingDebt: 22000,
    housingExpense: 35000,
    cibil: 792,
    productIdx: 2,
    amount: 4500000,
    tenor: 180,
    purpose: 'Purchase of 3BHK flat in Dwarka Expressway',
    status: 'APPROVED',
  },
  {
    id: 'ind-002',
    name: 'Priya Nair',
    email: 'priya.nair@outlook.com',
    phone: '+91 98203 45602',
    pan: 'BBVPN2302B',
    city: 'Bengaluru, Karnataka',
    address: '15/B 100 Feet Rd, Indiranagar',
    employer: 'Infosys Ltd',
    jobTitle: 'Senior Project Manager',
    yearsEmployed: 6.0,
    income: 145000,
    existingDebt: 18000,
    housingExpense: 28000,
    cibil: 765,
    productIdx: 0,
    amount: 800000,
    tenor: 36,
    purpose: 'Home renovation and modular kitchen setup',
    status: 'UNDER_REVIEW',
  },
  {
    id: 'ind-003',
    name: 'Rajesh Iyer',
    email: 'rajesh.iyer@gmail.com',
    phone: '+91 98404 56703',
    pan: 'CCKRI3403C',
    city: 'Chennai, Tamil Nadu',
    address: '77 Luz Church Road, Mylapore',
    employer: 'Zoho Corporation',
    jobTitle: 'Staff Infrastructure Engineer',
    yearsEmployed: 8.2,
    income: 160000,
    existingDebt: 15000,
    housingExpense: 30000,
    cibil: 810,
    productIdx: 2,
    amount: 3500000,
    tenor: 120,
    purpose: 'Residential plot construction in OMR corridor',
    status: 'DISBURSED',
  },
  {
    id: 'ind-004',
    name: 'Sunita Sen',
    email: 'sunita.sen@yahoo.co.in',
    phone: '+91 98305 67804',
    pan: 'DDPSS4504D',
    city: 'Kolkata, West Bengal',
    address: '28 Southern Avenue, Lake Gardens',
    employer: 'Sen & Associates Healthcare',
    jobTitle: 'Chief Clinical Biochemist',
    yearsEmployed: 9.0,
    income: 120000,
    existingDebt: 12000,
    housingExpense: 22000,
    cibil: 745,
    productIdx: 0,
    amount: 500000,
    tenor: 24,
    purpose: 'Medical diagnostics lab equipment upgrade',
    status: 'DOCUMENTS_VERIFIED',
  },
  {
    id: 'ind-005',
    name: 'Vikramaditya Rao',
    email: 'vikram.rao@gmail.com',
    phone: '+91 98496 78905',
    pan: 'EEVVR5605E',
    city: 'Hyderabad, Telangana',
    address: '8-2-293 Banjara Hills Road No 14',
    employer: "Dr. Reddy's Laboratories",
    jobTitle: 'Principal Formulation Scientist',
    yearsEmployed: 10.5,
    income: 210000,
    existingDebt: 35000,
    housingExpense: 40000,
    cibil: 778,
    productIdx: 1,
    amount: 1500000,
    tenor: 60,
    purpose: 'Hybrid electric luxury SUV acquisition',
    status: 'RISK_ASSESSED',
  },
  {
    id: 'ind-006',
    name: 'Meera Kulkarni',
    email: 'meera.kulkarni@gmail.com',
    phone: '+91 98227 89006',
    pan: 'FFPMK6706F',
    city: 'Pune, Maharashtra',
    address: '104 FC Road, Shivaji Nagar',
    employer: 'Persistent Systems',
    jobTitle: 'Technical Specialist',
    yearsEmployed: 4.8,
    income: 115000,
    existingDebt: 10000,
    housingExpense: 24000,
    cibil: 752,
    productIdx: 0,
    amount: 400000,
    tenor: 36,
    purpose: 'Higher education executive MBA fee funding',
    status: 'SUBMITTED',
  },
  {
    id: 'ind-007',
    name: 'Arjun Reddy',
    email: 'arjun.reddy@gmail.com',
    phone: '+91 98488 90107',
    pan: 'GGPAR7807G',
    city: 'Hyderabad, Telangana',
    address: '401 Jubilee Hills Road No 36',
    employer: 'Reddy Precision Engineering',
    jobTitle: 'Managing Partner',
    yearsEmployed: 11.0,
    income: 290000,
    existingDebt: 45000,
    housingExpense: 50000,
    cibil: 820,
    productIdx: 2,
    amount: 5500000,
    tenor: 180,
    purpose: 'Residential villa construction in Financial District',
    status: 'APPROVED',
  },
  {
    id: 'ind-008',
    name: 'Ananya Chatterjee',
    email: 'ananya.chatterjee@gmail.com',
    phone: '+91 98319 01208',
    pan: 'HHPAC8908H',
    city: 'Kolkata, West Bengal',
    address: '12 Ballygunge Circular Road',
    employer: 'Cognizant Technology Solutions',
    jobTitle: 'Associate Director',
    yearsEmployed: 8.5,
    income: 175000,
    existingDebt: 25000,
    housingExpense: 32000,
    cibil: 788,
    productIdx: 2,
    amount: 4200000,
    tenor: 180,
    purpose: 'Apartment purchase in New Town Action Area II',
    status: 'UNDER_REVIEW',
  },
  {
    id: 'ind-009',
    name: 'Harpreet Singh',
    email: 'harpreet.singh@gmail.com',
    phone: '+91 98140 12309',
    pan: 'IIJHS9009I',
    city: 'Chandigarh, Punjab',
    address: 'Sector 9-D, Madhya Marg',
    employer: 'Kisan Agrotech Pvt Ltd',
    jobTitle: 'Director of Supply Chain',
    yearsEmployed: 12.0,
    income: 195000,
    existingDebt: 28000,
    housingExpense: 30000,
    cibil: 770,
    productIdx: 1,
    amount: 2200000,
    tenor: 60,
    purpose: 'Commercial multi-axle carrier vehicle purchase',
    status: 'DISBURSED',
  },
  {
    id: 'ind-010',
    name: 'Deepika Joshi',
    email: 'deepika.joshi@gmail.com',
    phone: '+91 98291 23410',
    pan: 'JJPDS0110J',
    city: 'Jaipur, Rajasthan',
    address: '52 Malviya Nagar, JLN Marg',
    employer: 'Rajasthan State Handloom Dev Corp',
    jobTitle: 'Senior Design Consultant',
    yearsEmployed: 5.2,
    income: 95000,
    existingDebt: 8000,
    housingExpense: 18000,
    cibil: 735,
    productIdx: 0,
    amount: 350000,
    tenor: 24,
    purpose: 'Artisanal textile workshop studio renovation',
    status: 'DOCUMENTS_PENDING',
  },
  {
    id: 'ind-011',
    name: 'Rohan Deshmukh',
    email: 'rohan.deshmukh@gmail.com',
    phone: '+91 98212 34511',
    pan: 'KKPRD1211K',
    city: 'Mumbai, Maharashtra',
    address: 'Flat 14B, Sea Green Towers, Worli',
    employer: 'Morgan Stanley India',
    jobTitle: 'Vice President - Risk Analytics',
    yearsEmployed: 9.3,
    income: 320000,
    existingDebt: 50000,
    housingExpense: 65000,
    cibil: 825,
    productIdx: 2,
    amount: 8500000,
    tenor: 240,
    purpose: 'Luxury 3BHK flat in Wadala development',
    status: 'APPROVED',
  },
  {
    id: 'ind-012',
    name: 'Kavita Pillai',
    email: 'kavita.pillai@gmail.com',
    phone: '+91 98463 45612',
    pan: 'LLPKP2312L',
    city: 'Kochi, Kerala',
    address: 'Marine Drive Waterfront Enclave',
    employer: 'Cochin Shipyard Ltd',
    jobTitle: 'Senior Marine Engineer',
    yearsEmployed: 7.0,
    income: 130000,
    existingDebt: 14000,
    housingExpense: 25000,
    cibil: 760,
    productIdx: 2,
    amount: 3200000,
    tenor: 144,
    purpose: 'Waterfront duplex construction in Kakkanad',
    status: 'RISK_ASSESSED',
  },
  {
    id: 'ind-013',
    name: 'Aditya Verma',
    email: 'aditya.verma@gmail.com',
    phone: '+91 98394 56713',
    pan: 'MMPAV3413M',
    city: 'Lucknow, Uttar Pradesh',
    address: 'B-18 Gomti Nagar, Vibhuti Khand',
    employer: 'HCL Technologies',
    jobTitle: 'Principal Technical Lead',
    yearsEmployed: 6.5,
    income: 125000,
    existingDebt: 15000,
    housingExpense: 22000,
    cibil: 740,
    productIdx: 0,
    amount: 600000,
    tenor: 36,
    purpose: 'Family medical emergency consolidation',
    status: 'SUBMITTED',
  },
  {
    id: 'ind-014',
    name: 'Sneha Patel',
    email: 'sneha.patel@gmail.com',
    phone: '+91 98255 67814',
    pan: 'NNPSP4514N',
    city: 'Ahmedabad, Gujarat',
    address: '402 Sindhu Bhavan Marg, Bodakdev',
    employer: 'Zydus Lifesciences',
    jobTitle: 'Regulatory Affairs Manager',
    yearsEmployed: 7.8,
    income: 140000,
    existingDebt: 16000,
    housingExpense: 26000,
    cibil: 772,
    productIdx: 2,
    amount: 3800000,
    tenor: 180,
    purpose: 'Residential bungalow purchase near SG Highway',
    status: 'DOCUMENTS_VERIFIED',
  },
  {
    id: 'ind-015',
    name: 'Karthik Subramanian',
    email: 'karthik.subramanian@gmail.com',
    phone: '+91 98806 78915',
    pan: 'OOPKS5615O',
    city: 'Bengaluru, Karnataka',
    address: '78 HSR Layout Sector 4',
    employer: 'Flipkart Internet Pvt Ltd',
    jobTitle: 'Principal Product Manager',
    yearsEmployed: 9.0,
    income: 260000,
    existingDebt: 38000,
    housingExpense: 48000,
    cibil: 805,
    productIdx: 2,
    amount: 6500000,
    tenor: 180,
    purpose: 'Villa acquisition in Sarjapur Road',
    status: 'DISBURSED',
  },
  {
    id: 'ind-016',
    name: 'Pooja Agarwal',
    email: 'pooja.agarwal@gmail.com',
    phone: '+91 98267 89016',
    pan: 'PPQPA6716P',
    city: 'Indore, Madhya Pradesh',
    address: '88 Vijay Nagar, AB Road',
    employer: 'Agarwal Agro Trading Co',
    jobTitle: 'Partner - Finance',
    yearsEmployed: 8.0,
    income: 155000,
    existingDebt: 20000,
    housingExpense: 25000,
    cibil: 758,
    productIdx: 1,
    amount: 1400000,
    tenor: 48,
    purpose: 'Executive company vehicle fleet purchase',
    status: 'UNDER_REVIEW',
  },
  {
    id: 'ind-017',
    name: 'Siddharth Malhotra',
    email: 'siddharth.malhotra@gmail.com',
    phone: '+91 98108 90117',
    pan: 'QQPSM7817Q',
    city: 'Gurugram, Haryana',
    address: 'Penthouse 18, Golf Course Road DLF Phase 5',
    employer: 'McKinsey & Company',
    jobTitle: 'Associate Partner',
    yearsEmployed: 11.5,
    income: 350000,
    existingDebt: 55000,
    housingExpense: 75000,
    cibil: 830,
    productIdx: 2,
    amount: 9500000,
    tenor: 240,
    purpose: 'Apartment purchase in The Camellias',
    status: 'APPROVED',
  },
  {
    id: 'ind-018',
    name: 'Neha Choudhury',
    email: 'neha.choudhury@gmail.com',
    phone: '+91 98619 01218',
    pan: 'RRRNC8918R',
    city: 'Bhubaneswar, Odisha',
    address: '61 Janpath, Saheed Nagar',
    employer: 'NTPC Eastern Region',
    jobTitle: 'Deputy General Manager',
    yearsEmployed: 9.8,
    income: 165000,
    existingDebt: 22000,
    housingExpense: 28000,
    cibil: 782,
    productIdx: 0,
    amount: 750000,
    tenor: 48,
    purpose: 'Rooftop solar and home battery installation',
    status: 'RISK_ASSESSED',
  },
  {
    id: 'ind-019',
    name: 'Manoj Tiwari',
    email: 'manoj.tiwari@gmail.com',
    phone: '+91 98350 12319',
    pan: 'SSPMT9019S',
    city: 'Patna, Bihar',
    address: '14 Boring Road, Sri Krishna Puri',
    employer: 'Tiwari Diagnostic Imaging',
    jobTitle: 'Consultant Radiologist & MD',
    yearsEmployed: 12.0,
    income: 190000,
    existingDebt: 32000,
    housingExpense: 30000,
    cibil: 768,
    productIdx: 1,
    amount: 1800000,
    tenor: 60,
    purpose: 'Emergency medical response ambulance vehicle',
    status: 'DOCUMENTS_VERIFIED',
  },
  {
    id: 'ind-020',
    name: 'Ritu Menon',
    email: 'ritu.menon@gmail.com',
    phone: '+91 98471 23420',
    pan: 'TTPRM0120T',
    city: 'Thiruvananthapuram, Kerala',
    address: '22 Kowdiar Avenue',
    employer: 'ISRO - VSSC Centre',
    jobTitle: 'Scientist / Engineer - SG',
    yearsEmployed: 8.4,
    income: 150000,
    existingDebt: 18000,
    housingExpense: 26000,
    cibil: 795,
    productIdx: 2,
    amount: 3600000,
    tenor: 144,
    purpose: 'Ancestral home heritage restoration',
    status: 'APPROVED',
  },
  {
    id: 'ind-021',
    name: 'Alok Gupta',
    email: 'alok.gupta@gmail.com',
    phone: '+91 98182 34521',
    pan: 'UUPAG1221U',
    city: 'Noida, Uttar Pradesh',
    address: 'Tower 4, Sector 128 Express Highway',
    employer: 'Samsung R&D Institute',
    jobTitle: 'Chief Staff Architect',
    yearsEmployed: 10.2,
    income: 225000,
    existingDebt: 34000,
    housingExpense: 42000,
    cibil: 790,
    productIdx: 2,
    amount: 5500000,
    tenor: 180,
    purpose: 'Golf course facing apartment in Sector 150',
    status: 'DOCUMENTS_VERIFIED',
  },
  {
    id: 'ind-022',
    name: 'Divya Sundaram',
    email: 'divya.sundaram@gmail.com',
    phone: '+91 98423 45622',
    pan: 'VVPSD2322V',
    city: 'Coimbatore, Tamil Nadu',
    address: '90 Race Course Road',
    employer: 'Lakshmi Machine Works',
    jobTitle: 'Senior Metallurgy Engineer',
    yearsEmployed: 4.5,
    income: 110000,
    existingDebt: 12000,
    housingExpense: 20000,
    cibil: 748,
    productIdx: 0,
    amount: 450000,
    tenor: 36,
    purpose: 'Solar micro-grid setup for residence',
    status: 'SUBMITTED',
  },
  {
    id: 'ind-023',
    name: 'Gaurav Bhatia',
    email: 'gaurav.bhatia@gmail.com',
    phone: '+91 98154 56723',
    pan: 'WWPGB3423W',
    city: 'Amritsar, Punjab',
    address: '18 Mall Road, Civil Lines',
    employer: 'Golden Hospitality Group',
    jobTitle: 'General Manager',
    yearsEmployed: 6.8,
    income: 135000,
    existingDebt: 22000,
    housingExpense: 24000,
    cibil: 730,
    productIdx: 1,
    amount: 1200000,
    tenor: 48,
    purpose: 'Luxury passenger coach for hospitality clients',
    status: 'UNDER_REVIEW',
  },
  {
    id: 'ind-024',
    name: 'Swati Mukhopadhyay',
    email: 'swati.mukherjee@gmail.com',
    phone: '+91 98325 67824',
    pan: 'XXPSM4524X',
    city: 'Durgapur, West Bengal',
    address: 'B-4 City Centre, Bidhan Nagar',
    employer: 'SAIL Durgapur Steel Plant',
    jobTitle: 'Principal Metallurgical Consultant',
    yearsEmployed: 7.2,
    income: 140000,
    existingDebt: 16000,
    housingExpense: 25000,
    cibil: 762,
    productIdx: 2,
    amount: 2800000,
    tenor: 120,
    purpose: 'Duplex villa construction in Greenfield City',
    status: 'DISBURSED',
  },
  {
    id: 'ind-025',
    name: 'Nikhil Hegde',
    email: 'nikhil.hegde@gmail.com',
    phone: '+91 98456 78925',
    pan: 'YYPNH5625Y',
    city: 'Mangaluru, Karnataka',
    address: '101 Kadri Hills',
    employer: 'Hegde Coastal Logistics',
    jobTitle: 'Fleet Operations Director',
    yearsEmployed: 8.5,
    income: 170000,
    existingDebt: 26000,
    housingExpense: 28000,
    cibil: 775,
    productIdx: 1,
    amount: 2500000,
    tenor: 60,
    purpose: 'Refrigerated container truck acquisition',
    status: 'APPROVED',
  },
  {
    id: 'ind-026',
    name: 'Shalini Saxena',
    email: 'shalini.saxena@gmail.com',
    phone: '+91 98277 89026',
    pan: 'ZZPSS6726Z',
    city: 'Bhopal, Madhya Pradesh',
    address: '4 Arera Colony, E-3',
    employer: 'BHEL Bhopal',
    jobTitle: 'Senior Design Engineer',
    yearsEmployed: 6.0,
    income: 125000,
    existingDebt: 15000,
    housingExpense: 22000,
    cibil: 755,
    productIdx: 0,
    amount: 550000,
    tenor: 36,
    purpose: "Daughter's professional engineering tuition fees",
    status: 'RISK_ASSESSED',
  },
  {
    id: 'ind-027',
    name: 'Varun Nambiar',
    email: 'varun.nambiar@gmail.com',
    phone: '+91 98478 90127',
    pan: 'AAPVN7827A',
    city: 'Kozhikode, Kerala',
    address: '52 Wayanad Road, East Hill',
    employer: 'Malabar Tech Labs',
    jobTitle: 'Co-founder & CTO',
    yearsEmployed: 9.1,
    income: 190000,
    existingDebt: 25000,
    housingExpense: 30000,
    cibil: 785,
    productIdx: 0,
    amount: 900000,
    tenor: 36,
    purpose: 'Personal cloud workstation cluster installation',
    status: 'DOCUMENTS_VERIFIED',
  },
  {
    id: 'ind-028',
    name: 'Shreya Singhal',
    email: 'shreya.singhal@gmail.com',
    phone: '+91 98379 01228',
    pan: 'BBPSC8928B',
    city: 'Dehradun, Uttarakhand',
    address: '19 Rajpur Road',
    employer: 'Singhal & Co Chambers',
    jobTitle: 'Senior High Court Advocate',
    yearsEmployed: 10.0,
    income: 210000,
    existingDebt: 30000,
    housingExpense: 35000,
    cibil: 798,
    productIdx: 2,
    amount: 5200000,
    tenor: 180,
    purpose: 'Hillside cottage and legal chamber establishment',
    status: 'APPROVED',
  },
  {
    id: 'ind-029',
    name: 'Abhinav Pandey',
    email: 'abhinav.pandey@gmail.com',
    phone: '+91 98380 12329',
    pan: 'CCPAP9029C',
    city: 'Varanasi, Uttar Pradesh',
    address: '88 Sigra Road, Mahmoorganj',
    employer: 'Banaras Silk Weavers Guild',
    jobTitle: 'General Secretary',
    yearsEmployed: 7.0,
    income: 145000,
    existingDebt: 20000,
    housingExpense: 24000,
    cibil: 742,
    productIdx: 1,
    amount: 1100000,
    tenor: 48,
    purpose: 'Commercial vehicle for handloom textile distribution',
    status: 'UNDER_REVIEW',
  },
  {
    id: 'ind-030',
    name: 'Nandini Das',
    email: 'nandini.das@gmail.com',
    phone: '+91 98641 23430',
    pan: 'DDPND0130D',
    city: 'Guwahati, Assam',
    address: '15 GS Road, Christian Basti',
    employer: 'Oil India Ltd',
    jobTitle: 'Senior Petroleum Geologist',
    yearsEmployed: 8.6,
    income: 170000,
    existingDebt: 22000,
    housingExpense: 28000,
    cibil: 780,
    productIdx: 2,
    amount: 4000000,
    tenor: 144,
    purpose: 'Brahmaputra riverside apartment purchase',
    status: 'DOCUMENTS_VERIFIED',
  },
  {
    id: 'ind-031',
    name: 'Prateek Bansal',
    email: 'prateek.bansal@gmail.com',
    phone: '+91 98122 34531',
    pan: 'EEPPB1231E',
    city: 'Faridabad, Haryana',
    address: 'Sector 15 Main Market Road',
    employer: 'Bansal Precision Fasteners',
    jobTitle: 'Managing Director',
    yearsEmployed: 11.0,
    income: 240000,
    existingDebt: 40000,
    housingExpense: 38000,
    cibil: 765,
    productIdx: 1,
    amount: 2400000,
    tenor: 60,
    purpose: 'Commercial delivery fleet vehicle acquisition',
    status: 'APPROVED',
  },
  {
    id: 'ind-032',
    name: 'Tanvi Trivedi',
    email: 'tanvi.trivedi@gmail.com',
    phone: '+91 98243 45632',
    pan: 'FFPTT2332F',
    city: 'Vadodara, Gujarat',
    address: '72 Alkapuri, RC Dutt Road',
    employer: 'Larsen & Toubro Ltd',
    jobTitle: 'Senior Structural Engineer',
    yearsEmployed: 6.2,
    income: 135000,
    existingDebt: 16000,
    housingExpense: 24000,
    cibil: 764,
    productIdx: 0,
    amount: 450000,
    tenor: 24,
    purpose: 'Home electrical grid solar retrofit',
    status: 'SUBMITTED',
  },
  {
    id: 'ind-033',
    name: 'Sachin Sawant',
    email: 'sachin.sawant@gmail.com',
    phone: '+91 98234 56733',
    pan: 'GGPSZ3433G',
    city: 'Nashik, Maharashtra',
    address: '44 Gangapur Road',
    employer: 'Sula Vineyards Ltd',
    jobTitle: 'Viticulture Operations Manager',
    yearsEmployed: 5.5,
    income: 115000,
    existingDebt: 14000,
    housingExpense: 20000,
    cibil: 750,
    productIdx: 0,
    amount: 350000,
    tenor: 36,
    purpose: 'Micro-drip irrigation equipment installation',
    status: 'UNDER_REVIEW',
  },
  {
    id: 'ind-034',
    name: 'Rashmi Balakrishnan',
    email: 'rashmi.bala@gmail.com',
    phone: '+91 98865 67834',
    pan: 'HHPRA4534H',
    city: 'Mysuru, Karnataka',
    address: '12 Gokulam 3rd Stage',
    employer: 'CFTRI Research Staff',
    jobTitle: 'Principal Food Scientist',
    yearsEmployed: 8.0,
    income: 140000,
    existingDebt: 18000,
    housingExpense: 24000,
    cibil: 774,
    productIdx: 2,
    amount: 3400000,
    tenor: 144,
    purpose: 'Eco-friendly sustainable home near Chamundi Hills',
    status: 'DISBURSED',
  },
  {
    id: 'ind-035',
    name: 'Tarun Goswami',
    email: 'tarun.goswami@gmail.com',
    phone: '+91 98356 78935',
    pan: 'IIPTG5635I',
    city: 'Ranchi, Jharkhand',
    address: '29 Kanke Road',
    employer: 'Central Coalfields Ltd (CCL)',
    jobTitle: 'Deputy Chief Mining Engineer',
    yearsEmployed: 7.5,
    income: 150000,
    existingDebt: 24000,
    housingExpense: 25000,
    cibil: 738,
    productIdx: 0,
    amount: 650000,
    tenor: 48,
    purpose: "Son's medical college tuition and hostel accommodation",
    status: 'DOCUMENTS_PENDING',
  },
  {
    id: 'ind-036',
    name: 'Pallavi Shinde',
    email: 'pallavi.shinde@gmail.com',
    phone: '+91 98227 89036',
    pan: 'JJFPS6736J',
    city: 'Nagpur, Maharashtra',
    address: '9 Civil Lines, Palm Road',
    employer: 'Persistent Systems Nagpur',
    jobTitle: 'Scrum Master & QA Manager',
    yearsEmployed: 6.4,
    income: 120000,
    existingDebt: 15000,
    housingExpense: 22000,
    cibil: 760,
    productIdx: 2,
    amount: 2900000,
    tenor: 120,
    purpose: 'Row house purchase near MIHAN Special Economic Zone',
    status: 'RISK_ASSESSED',
  },
  {
    id: 'ind-037',
    name: 'Vishal Khatri',
    email: 'vishal.khatri@gmail.com',
    phone: '+91 98258 90137',
    pan: 'KKPVK7837K',
    city: 'Surat, Gujarat',
    address: '501 Ring Road Diamond Market',
    employer: 'Khatri Gems Export',
    jobTitle: 'Senior Partner',
    yearsEmployed: 12.0,
    income: 310000,
    existingDebt: 48000,
    housingExpense: 55000,
    cibil: 815,
    productIdx: 1,
    amount: 2800000,
    tenor: 60,
    purpose: 'Armored secure bullion transport vehicle',
    status: 'APPROVED',
  },
  {
    id: 'ind-038',
    name: 'Ishita Ganguly',
    email: 'ishita.ganguly@gmail.com',
    phone: '+91 98309 01238',
    pan: 'LLPIG8938L',
    city: 'Asansol, West Bengal',
    address: '7 Burnpur Road',
    employer: 'Eastern Railway Hospital',
    jobTitle: 'Senior Anaesthesiologist',
    yearsEmployed: 8.5,
    income: 160000,
    existingDebt: 22000,
    housingExpense: 26000,
    cibil: 782,
    productIdx: 0,
    amount: 700000,
    tenor: 36,
    purpose: 'Solar power system installation for home and clinic',
    status: 'DOCUMENTS_VERIFIED',
  },
  {
    id: 'ind-039',
    name: 'Chetan Solanki',
    email: 'chetan.solanki@gmail.com',
    phone: '+91 98240 12339',
    pan: 'MMPCS9039M',
    city: 'Rajkot, Gujarat',
    address: '8 Yagnik Road',
    employer: 'Solanki Foundry & Pumps',
    jobTitle: 'Managing Director',
    yearsEmployed: 10.0,
    income: 230000,
    existingDebt: 38000,
    housingExpense: 36000,
    cibil: 758,
    productIdx: 1,
    amount: 2000000,
    tenor: 48,
    purpose: 'Distribution utility fleet vehicles',
    status: 'SUBMITTED',
  },
  {
    id: 'ind-040',
    name: 'Bhavna Venkatesh',
    email: 'bhavna.venkatesh@gmail.com',
    phone: '+91 98421 23440',
    pan: 'NNPBV0140N',
    city: 'Madurai, Tamil Nadu',
    address: '33 West Veli Street',
    employer: 'Aravind Eye Care System',
    jobTitle: 'Senior Refractive Surgeon',
    yearsEmployed: 9.5,
    income: 185000,
    existingDebt: 24000,
    housingExpense: 32000,
    cibil: 802,
    productIdx: 2,
    amount: 4800000,
    tenor: 180,
    purpose: 'Gated community luxury residence in KK Nagar',
    status: 'APPROVED',
  },
  {
    id: 'ind-041',
    name: 'Kunal Bhardwaj',
    email: 'kunal.bhardwaj@gmail.com',
    phone: '+91 98392 34541',
    pan: 'OOPKB1241O',
    city: 'Kanpur, Uttar Pradesh',
    address: '12 Civil Lines, Mall Road',
    employer: 'Bhardwaj Leather Exporters',
    jobTitle: 'Operations Lead',
    yearsEmployed: 4.2,
    income: 160000,
    existingDebt: 72000,
    housingExpense: 28000,
    cibil: 685,
    productIdx: 0,
    amount: 1500000,
    tenor: 36,
    purpose: 'Personal bridge financing for plant upgrades',
    status: 'REJECTED',
  },
  {
    id: 'ind-042',
    name: 'Aparna Shenoy',
    email: 'aparna.shenoy@gmail.com',
    phone: '+91 98453 45642',
    pan: 'PPQAS2342P',
    city: 'Udupi, Karnataka',
    address: '18 Manipal High Road',
    employer: 'Kasturba Medical College',
    jobTitle: 'Associate Professor of Pathology',
    yearsEmployed: 7.2,
    income: 135000,
    existingDebt: 16000,
    housingExpense: 24000,
    cibil: 776,
    productIdx: 2,
    amount: 3500000,
    tenor: 144,
    purpose: 'Hillside home in Manipal with coastal breeze architecture',
    status: 'DOCUMENTS_VERIFIED',
  },
  {
    id: 'ind-043',
    name: 'Mohit Jindal',
    email: 'mohit.jindal@gmail.com',
    phone: '+91 98144 56743',
    pan: 'QQPMJ3443Q',
    city: 'Ludhiana, Punjab',
    address: '90 Ferozepur Road',
    employer: 'Jindal Woolen Mills',
    jobTitle: 'Managing Partner',
    yearsEmployed: 11.2,
    income: 270000,
    existingDebt: 42000,
    housingExpense: 45000,
    cibil: 790,
    productIdx: 1,
    amount: 2600000,
    tenor: 48,
    purpose: 'Corporate logistics SUV and staff transport vehicles',
    status: 'DISBURSED',
  },
  {
    id: 'ind-044',
    name: 'Lavanya Krishnan',
    email: 'lavanya.krishnan@gmail.com',
    phone: '+91 98435 67844',
    pan: 'RRRLK4544R',
    city: 'Tiruchirappalli, Tamil Nadu',
    address: '45 Salai Road, Thillai Nagar',
    employer: 'National Institute of Technology Trichy',
    jobTitle: 'Professor of Electrical Engineering',
    yearsEmployed: 8.8,
    income: 155000,
    existingDebt: 18000,
    housingExpense: 26000,
    cibil: 808,
    productIdx: 2,
    amount: 3900000,
    tenor: 144,
    purpose: 'Solar powered independent house construction',
    status: 'APPROVED',
  },
  {
    id: 'ind-045',
    name: 'Devendra Chauhan',
    email: 'devendra.chauhan@gmail.com',
    phone: '+91 98376 78945',
    pan: 'SSSDC5645S',
    city: 'Agra, Uttar Pradesh',
    address: '16 Fatehabad Road, Tajganj',
    employer: 'Chauhan Inox Fabrication',
    jobTitle: 'Proprietor',
    yearsEmployed: 3.5,
    income: 110000,
    existingDebt: 58000,
    housingExpense: 22000,
    cibil: 630,
    productIdx: 0,
    amount: 800000,
    tenor: 24,
    purpose: 'Urgent debt consolidation and cash buffer',
    status: 'REJECTED',
  },
];

export const INDIAN_MOCK_USERS: User[] = INDIAN_BORROWER_PROFILES.map((p) => ({
  id: `usr-${p.id}`,
  email: p.email,
  fullName: p.name,
  role: 'APPLICANT',
  phone: p.phone,
  isActive: true,
}));

export const getIndianMockApplications = (products: LoanProduct[]): LoanApplication[] => {
  return INDIAN_BORROWER_PROFILES.map((p, idx) => {
    const prod = products[p.productIdx] || products[0];
  const refNum = `APP-2026-${(idx + 10).toString().padStart(4, '0')}`;
  const appId = `app-${p.id}`;

  const emi = calculateEmi(p.amount, prod.baseApr, p.tenor);
  const dti = calculateDti(p.income, p.existingDebt, emi);
  const disposable = calculateDisposableIncome(p.income, p.existingDebt, p.housingExpense, emi);

  const docs: ApplicationDocument[] = [
    {
      id: `doc-${p.id}-pan`,
      applicationId: appId,
      documentType: 'PAN Card (NSDL)',
      originalFilename: `PAN_${p.name.replace(/\s+/g, '_')}.pdf`,
      mimeType: 'application/pdf',
      fileSizeBytes: 1420000,
      verificationStatus: p.status === 'DOCUMENTS_PENDING' ? 'PENDING' : 'VERIFIED',
      verificationRemarks: p.status === 'DOCUMENTS_PENDING' ? undefined : 'NSDL Tax database e-KYC verified.',
      uploadedAt: '2026-09-24T10:00:00Z',
      verifiedAt: p.status === 'DOCUMENTS_PENDING' ? undefined : '2026-09-24T14:30:00Z',
      verifiedByName: p.status === 'DOCUMENTS_PENDING' ? undefined : 'David Vance',
    },
    {
      id: `doc-${p.id}-aadhaar`,
      applicationId: appId,
      documentType: 'Aadhaar Card (UIDAI XML)',
      originalFilename: `Aadhaar_${p.name.replace(/\s+/g, '_')}.pdf`,
      mimeType: 'application/pdf',
      fileSizeBytes: 2150000,
      verificationStatus: p.status === 'DOCUMENTS_PENDING' ? 'PENDING' : 'VERIFIED',
      verificationRemarks: p.status === 'DOCUMENTS_PENDING' ? undefined : 'UIDAI biometric OTP match verified.',
      uploadedAt: '2026-09-24T10:05:00Z',
      verifiedAt: p.status === 'DOCUMENTS_PENDING' ? undefined : '2026-09-24T14:32:00Z',
      verifiedByName: p.status === 'DOCUMENTS_PENDING' ? undefined : 'David Vance',
    },
    {
      id: `doc-${p.id}-salary`,
      applicationId: appId,
      documentType: 'Salary Slips (3 Months)',
      originalFilename: `PaySlips_${p.name.replace(/\s+/g, '_')}.pdf`,
      mimeType: 'application/pdf',
      fileSizeBytes: 3200000,
      verificationStatus: p.status === 'DOCUMENTS_PENDING' ? 'PENDING' : 'VERIFIED',
      verificationRemarks: p.status === 'DOCUMENTS_PENDING' ? undefined : `Direct employer payroll deposit verified at ₹${p.income.toLocaleString('en-IN')}/mo.`,
      uploadedAt: '2026-09-24T10:10:00Z',
      verifiedAt: p.status === 'DOCUMENTS_PENDING' ? undefined : '2026-09-24T14:35:00Z',
      verifiedByName: p.status === 'DOCUMENTS_PENDING' ? undefined : 'David Vance',
    },
  ];

  let riskAssessment: RiskAssessment | undefined;
  if (['RISK_ASSESSED', 'APPROVED', 'DISBURSED', 'REJECTED'].includes(p.status)) {
    const isApprovedOrGood = p.cibil >= 720 && dti <= 50;
    riskAssessment = {
      id: `risk-${p.id}`,
      applicationId: appId,
      calculatedDti: dti,
      calculatedEmi: emi,
      disposableIncome: disposable,
      internalRiskScore: p.cibil,
      riskTier: p.cibil >= 780 && dti <= 40 ? 'LOW' : (p.cibil >= 720 && dti <= 50 ? 'MEDIUM' : 'HIGH'),
      recommendation: isApprovedOrGood ? 'APPROVE' : 'REJECT',
      scoreFactors: [
        { name: 'CIBIL Bureau Score', evaluated: `${p.cibil}`, threshold: '≥ 700', status: p.cibil >= 700 ? 'PASS' : 'FAIL' },
        { name: 'Debt-to-Income (DTI)', evaluated: `${dti}%`, threshold: `≤ ${prod.maxDtiRatio}%`, status: dti <= prod.maxDtiRatio ? 'PASS' : 'FAIL' },
        { name: 'Disposable Income', evaluated: `₹${disposable.toLocaleString('en-IN')}`, threshold: '> ₹15,000', status: disposable > 15000 ? 'PASS' : 'FAIL' },
        { name: 'Tenor Adequacy', evaluated: `${p.tenor}m`, threshold: `≤ ${prod.maxTenorMonths}m`, status: 'PASS' },
      ],
      evaluatedAt: '2026-09-25T11:00:00Z',
    };
  }

  let decision: LoanDecision | undefined;
  if (['APPROVED', 'DISBURSED', 'REJECTED'].includes(p.status)) {
    decision = {
      id: `dec-${p.id}`,
      applicationId: appId,
      decision: p.status === 'REJECTED' ? 'REJECTED' : 'APPROVED',
      approvedAmount: p.status === 'REJECTED' ? undefined : p.amount,
      approvedApr: p.status === 'REJECTED' ? undefined : prod.baseApr,
      approvedTenorMonths: p.status === 'REJECTED' ? undefined : p.tenor,
      conditions: p.status === 'REJECTED' ? undefined : 'National Automated Clearing House (NACH) e-mandate registration.',
      rejectionReasonCode: p.status === 'REJECTED' ? 'HIGH_DTI_EXCEEDS_POLICY' : undefined,
      underwriterNotes: p.status === 'REJECTED'
        ? 'DTI exceeds maximum institutional guidelines and CIBIL score indicates high risk tier.'
        : `Prime applicant profile sanctioned with CIBIL ${p.cibil} and healthy debt service coverage ratio.`,
      decidedByName: 'Katherine Reed',
      decidedAt: '2026-09-25T16:00:00Z',
    };
  }

  return {
    id: appId,
    referenceNumber: refNum,
    applicantId: `usr-${p.id}`,
    productId: prod.id,
    product: prod,
    assignedOfficerId: 'usr-officer-1',
    assignedOfficerName: 'David Vance',
    status: p.status,
    requestedAmount: p.amount,
    requestedTenorMonths: p.tenor,
    purpose: p.purpose,
    personal: {
      fullName: p.name,
      email: p.email,
      phone: p.phone,
      dateOfBirth: '1988-04-15',
      residentialAddress: `${p.address}, ${p.city}`,
      taxIdMasked: `******${p.pan.slice(-4)}`,
    },
    financial: {
      employmentType: ['Proprietor', 'Partner', 'Managing Partner', 'Director', 'Managing Director'].some((t) =>
        p.jobTitle.includes(t)
      )
        ? 'SELF_EMPLOYED'
        : 'SALARIED',
      employerName: p.employer,
      jobTitle: p.jobTitle,
      yearsEmployed: p.yearsEmployed,
      grossMonthlyIncome: p.income,
      existingMonthlyDebt: p.existingDebt,
      housingExpense: p.housingExpense,
      creditScoreDeclared: p.cibil,
    },
    documents: docs,
    riskAssessment,
    decision,
    submittedAt: '2026-09-24T09:30:00Z',
    createdAt: '2026-09-24T09:00:00Z',
    updatedAt: '2026-09-25T16:00:00Z',
  };
});
};
