import type { LoanProduct, LoanApplication, User, AuditLog } from '../types';

export const INITIAL_PRODUCTS: LoanProduct[] = [
  {
    id: 'prod-personal',
    code: 'PL-UNSEC',
    name: 'Personal Unsecured Loan',
    description: 'Fixed-rate financing for personal expenditures, debt consolidation, or unexpected needs.',
    minAmount: 5000,
    maxAmount: 50000,
    minTenorMonths: 12,
    maxTenorMonths: 60,
    baseApr: 10.5,
    maxDtiRatio: 45,
    requiredDocuments: [
      { code: 'GOV_ID', title: 'Government Photo ID', description: 'Passport or Driver License', mandatory: true },
      { code: 'W2_INCOME', title: 'W-2 / Tax Return (2025)', description: 'Most recent official annual tax filing', mandatory: true },
      { code: 'BANK_STMT', title: 'Bank Statements (90 Days)', description: 'Last 3 consecutive months of primary checking account', mandatory: true },
    ],
    isActive: true,
  },
  {
    id: 'prod-auto',
    code: 'AUTO-SEC',
    name: 'Automotive Secured Loan',
    description: 'Competitive vehicle financing with asset lien protection and flexible tenor.',
    minAmount: 10000,
    maxAmount: 85000,
    minTenorMonths: 24,
    maxTenorMonths: 72,
    baseApr: 7.25,
    maxDtiRatio: 48,
    requiredDocuments: [
      { code: 'GOV_ID', title: 'Government Photo ID', description: 'Passport or Driver License', mandatory: true },
      { code: 'PAYSLIPS', title: 'Recent Paystubs (2 Months)', description: 'Consecutive monthly proof of earnings', mandatory: true },
      { code: 'DEALER_INVOICE', title: 'Dealer Purchase Order', description: 'Itemized vehicle specification and VIN', mandatory: true },
    ],
    isActive: true,
  },
  {
    id: 'prod-home',
    code: 'HOME-EQ',
    name: 'Home Improvement & Equity',
    description: 'Leverage residential equity for property expansion, major renovations, or repairs.',
    minAmount: 25000,
    maxAmount: 250000,
    minTenorMonths: 36,
    maxTenorMonths: 180,
    baseApr: 6.85,
    maxDtiRatio: 43,
    requiredDocuments: [
      { code: 'GOV_ID', title: 'Government Photo ID', description: 'Passport or Driver License', mandatory: true },
      { code: 'W2_INCOME', title: 'W-2 / 1040 Tax Return (2 Years)', description: 'Federal tax returns with all schedules', mandatory: true },
      { code: 'TITLE_DEED', title: 'Property Deed / Valuation', description: 'Current title deed and municipal assessment', mandatory: true },
      { code: 'BANK_STMT', title: 'Bank Statements (90 Days)', description: 'Last 3 consecutive months of accounts', mandatory: true },
    ],
    isActive: true,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-officer-1',
    email: 'd.vance@lapsbank.com',
    fullName: 'David Vance',
    role: 'LOAN_OFFICER',
    phone: '+1 (555) 234-5678',
    isActive: true,
  },
  {
    id: 'usr-analyst-1',
    email: 'k.reed@lapsbank.com',
    fullName: 'Katherine Reed',
    role: 'RISK_ANALYST',
    phone: '+1 (555) 345-6789',
    isActive: true,
  },
  {
    id: 'usr-applicant-1',
    email: 'alex.taylor@gmail.com',
    fullName: 'Alex Taylor',
    role: 'APPLICANT',
    phone: '+1 (555) 987-6543',
    isActive: true,
  },
  {
    id: 'usr-admin-1',
    email: 'admin@lapsbank.com',
    fullName: 'Sarah Sterling (Admin)',
    role: 'ADMIN',
    phone: '+1 (555) 111-2222',
    isActive: true,
  },
];

export const INITIAL_APPLICATIONS: LoanApplication[] = [
  {
    id: 'app-001',
    referenceNumber: 'APP-2026-0891',
    applicantId: 'usr-applicant-1',
    productId: 'prod-personal',
    product: INITIAL_PRODUCTS[0],
    assignedOfficerId: 'usr-officer-1',
    assignedOfficerName: 'David Vance',
    status: 'UNDER_REVIEW',
    requestedAmount: 45000,
    requestedTenorMonths: 36,
    purpose: 'Debt Consolidation & Credit Refinancing',
    personal: {
      fullName: 'Alex Taylor',
      email: 'alex.taylor@gmail.com',
      phone: '+1 (555) 987-6543',
      dateOfBirth: '1988-06-14',
      residentialAddress: '742 Evergreen Terrace, Springfield, OR 97477',
      taxIdMasked: '***-**-8421',
    },
    financial: {
      employmentType: 'SALARIED',
      employerName: 'Apex Industrial Holdings',
      jobTitle: 'Senior Systems Architect',
      yearsEmployed: 4.5,
      grossMonthlyIncome: 9200,
      existingMonthlyDebt: 1400,
      housingExpense: 1800,
      creditScoreDeclared: 762,
    },
    documents: [
      {
        id: 'doc-001',
        applicationId: 'app-001',
        documentType: 'Government Photo ID',
        originalFilename: 'US_Passport_AlexTaylor.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 2450000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: 'Identity verified against government passport database. Valid through 2031.',
        uploadedAt: '2026-09-24T10:14:00Z',
        verifiedAt: '2026-09-25T09:30:00Z',
        verifiedByName: 'David Vance',
      },
      {
        id: 'doc-002',
        applicationId: 'app-001',
        documentType: 'W-2 / Tax Return (2025)',
        originalFilename: 'W2_ApexIndustrial_2025.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 1850000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: 'Gross wages of ₹1,10,400 confirmed (₹9,200/mo). Matches declared income.',
        uploadedAt: '2026-09-24T10:15:30Z',
        verifiedAt: '2026-09-25T09:35:00Z',
        verifiedByName: 'David Vance',
      },
      {
        id: 'doc-003',
        applicationId: 'app-001',
        documentType: 'Bank Statements (90 Days)',
        originalFilename: 'Chase_Checking_Dec_Jan_Feb.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 3920000,
        verificationStatus: 'PENDING',
        verificationRemarks: 'Reviewing 90-day balance consistency and regular recurring salary deposits.',
        uploadedAt: '2026-09-24T10:18:00Z',
      },
    ],
    riskAssessment: {
      id: 'risk-001',
      applicationId: 'app-001',
      calculatedDti: 31.4,
      calculatedEmi: 1462.93,
      disposableIncome: 4537.07,
      internalRiskScore: 785,
      riskTier: 'LOW',
      recommendation: 'PRE-APPROVED for full requested amount at baseline APR.',
      scoreFactors: [
        { name: 'Debt-to-Income (DTI)', evaluated: '31.4%', threshold: '<= 45.0%', status: 'PASS' },
        { name: 'Credit Score Threshold', evaluated: '762', threshold: '>= 650', status: 'PASS' },
        { name: 'Employment Tenure', evaluated: '4.5 Years', threshold: '>= 2.0 Years', status: 'PASS' },
        { name: 'Disposable Income Cushion', evaluated: '₹4,537.07 / mo', threshold: '>= ₹1,500.00', status: 'PASS' },
      ],
      evaluatedAt: '2026-09-25T11:00:00Z',
    },
    submittedAt: '2026-09-24T10:20:00Z',
    createdAt: '2026-09-24T09:45:00Z',
    updatedAt: '2026-09-25T09:35:00Z',
  },
  {
    id: 'app-002',
    referenceNumber: 'APP-2026-0412',
    applicantId: 'usr-applicant-2',
    productId: 'prod-home',
    product: INITIAL_PRODUCTS[2],
    assignedOfficerId: 'usr-officer-1',
    assignedOfficerName: 'David Vance',
    status: 'DOCUMENTS_VERIFIED',
    requestedAmount: 65000,
    requestedTenorMonths: 60,
    purpose: 'Kitchen Remodeling and Solar Roof Installation',
    personal: {
      fullName: 'Elena Rostova',
      email: 'elena.rostova@gmail.com',
      phone: '+1 (555) 444-5555',
      dateOfBirth: '1982-11-03',
      residentialAddress: '1204 Pine Ridge Ave, Seattle, WA 98101',
      taxIdMasked: '***-**-5192',
    },
    financial: {
      employmentType: 'SALARIED',
      employerName: 'BioHealth Research Institute',
      jobTitle: 'Principal Biostatistician',
      yearsEmployed: 6.2,
      grossMonthlyIncome: 12500,
      existingMonthlyDebt: 2100,
      housingExpense: 2400,
      creditScoreDeclared: 790,
    },
    documents: [
      {
        id: 'doc-004',
        applicationId: 'app-002',
        documentType: 'Government Photo ID',
        originalFilename: 'WA_DL_ElenaRostova.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 1540000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: 'State DL verified.',
        uploadedAt: '2026-09-22T14:00:00Z',
        verifiedAt: '2026-09-23T11:00:00Z',
        verifiedByName: 'David Vance',
      },
      {
        id: 'doc-005',
        applicationId: 'app-002',
        documentType: 'W-2 / 1040 Tax Return (2 Years)',
        originalFilename: 'Federal_1040_2024_2025.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 4200000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: '2-year consistent income verified.',
        uploadedAt: '2026-09-22T14:05:00Z',
        verifiedAt: '2026-09-23T11:15:00Z',
        verifiedByName: 'David Vance',
      },
      {
        id: 'doc-006',
        applicationId: 'app-002',
        documentType: 'Property Deed / Valuation',
        originalFilename: 'Deed_PineRidge_Valuation.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 2900000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: 'LTV verified at 54% (under 75% limit).',
        uploadedAt: '2026-09-22T14:10:00Z',
        verifiedAt: '2026-09-23T11:20:00Z',
        verifiedByName: 'David Vance',
      },
    ],
    riskAssessment: {
      id: 'risk-002',
      applicationId: 'app-002',
      calculatedDti: 27.1,
      calculatedEmi: 1282.88,
      disposableIncome: 6717.12,
      internalRiskScore: 840,
      riskTier: 'LOW',
      recommendation: 'EXCELLENT: Low DTI, prime credit history, high disposable surplus.',
      scoreFactors: [
        { name: 'Debt-to-Income (DTI)', evaluated: '27.1%', threshold: '<= 43.0%', status: 'PASS' },
        { name: 'Credit Score Threshold', evaluated: '790', threshold: '>= 650', status: 'PASS' },
        { name: 'Loan-to-Value (LTV)', evaluated: '54.0%', threshold: '<= 75.0%', status: 'PASS' },
        { name: 'Disposable Income Cushion', evaluated: '₹6,717.12 / mo', threshold: '>= ₹2,000.00', status: 'PASS' },
      ],
      evaluatedAt: '2026-09-23T14:30:00Z',
    },
    submittedAt: '2026-09-22T14:15:00Z',
    createdAt: '2026-09-22T13:00:00Z',
    updatedAt: '2026-09-23T11:20:00Z',
  },
  {
    id: 'app-003',
    referenceNumber: 'APP-2026-0294',
    applicantId: 'usr-applicant-3',
    productId: 'prod-auto',
    product: INITIAL_PRODUCTS[1],
    assignedOfficerId: 'usr-officer-1',
    assignedOfficerName: 'David Vance',
    status: 'RISK_ASSESSED',
    requestedAmount: 52000,
    requestedTenorMonths: 48,
    purpose: 'New Commercial Van Purchase (Ford E-Transit)',
    personal: {
      fullName: 'Marcus Sterling',
      email: 'marcus.s@sterlingdelivery.com',
      phone: '+1 (555) 777-8899',
      dateOfBirth: '1979-04-20',
      residentialAddress: '88 Commerce Blvd, Denver, CO 80202',
      taxIdMasked: '***-**-3341',
    },
    financial: {
      employmentType: 'SELF_EMPLOYED',
      employerName: 'Sterling Express Couriers LLC',
      jobTitle: 'Managing Partner',
      yearsEmployed: 7.0,
      grossMonthlyIncome: 8800,
      existingMonthlyDebt: 2450,
      housingExpense: 1600,
      creditScoreDeclared: 672,
    },
    documents: [
      {
        id: 'doc-007',
        applicationId: 'app-003',
        documentType: 'Government Photo ID',
        originalFilename: 'CO_DL_MarcusSterling.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 1200000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: 'Driver license valid through 2029.',
        uploadedAt: '2026-09-20T08:00:00Z',
        verifiedAt: '2026-09-21T09:00:00Z',
        verifiedByName: 'David Vance',
      },
      {
        id: 'doc-008',
        applicationId: 'app-003',
        documentType: 'Recent Paystubs (2 Months)',
        originalFilename: 'SterlingCouriers_Draw_Statements.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 2100000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: 'Business distributions confirmed averaging ₹8,800/mo.',
        uploadedAt: '2026-09-20T08:15:00Z',
        verifiedAt: '2026-09-21T09:10:00Z',
        verifiedByName: 'David Vance',
      },
      {
        id: 'doc-009',
        applicationId: 'app-003',
        documentType: 'Dealer Purchase Order',
        originalFilename: 'DenverFord_PurchaseOrder_VIN9921.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 980000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: 'Dealer invoice confirmed ₹52,000 MSRP.',
        uploadedAt: '2026-09-20T08:30:00Z',
        verifiedAt: '2026-09-21T09:15:00Z',
        verifiedByName: 'David Vance',
      },
    ],
    riskAssessment: {
      id: 'risk-003',
      applicationId: 'app-003',
      calculatedDti: 42.1,
      calculatedEmi: 1251.42,
      disposableIncome: 3498.58,
      internalRiskScore: 685,
      riskTier: 'MEDIUM',
      recommendation: 'CONDITIONAL APPROVAL: DTI near 42% threshold; recommend 0.5% rate buffer.',
      scoreFactors: [
        { name: 'Debt-to-Income (DTI)', evaluated: '42.1%', threshold: '<= 48.0%', status: 'FLAG' },
        { name: 'Credit Score Threshold', evaluated: '672', threshold: '>= 650', status: 'PASS' },
        { name: 'Self-Employment Continuity', evaluated: '7.0 Years', threshold: '>= 3.0 Years', status: 'PASS' },
        { name: 'Asset Collateral Lien', evaluated: 'Commercial Vehicle', threshold: 'Eligible', status: 'PASS' },
      ],
      evaluatedAt: '2026-09-21T14:00:00Z',
    },
    submittedAt: '2026-09-20T08:45:00Z',
    createdAt: '2026-09-20T07:30:00Z',
    updatedAt: '2026-09-21T14:00:00Z',
  },
  {
    id: 'app-004',
    referenceNumber: 'APP-2026-0922',
    applicantId: 'usr-applicant-4',
    productId: 'prod-personal',
    product: INITIAL_PRODUCTS[0],
    assignedOfficerId: 'usr-officer-1',
    assignedOfficerName: 'David Vance',
    status: 'DOCUMENTS_PENDING',
    requestedAmount: 15000,
    requestedTenorMonths: 24,
    purpose: 'Medical Procedure & Emergency Reserve',
    personal: {
      fullName: 'James Wilson',
      email: 'jwilson@gmail.com',
      phone: '+1 (555) 321-4321',
      dateOfBirth: '1995-02-18',
      residentialAddress: '405 University St, Austin, TX 78701',
      taxIdMasked: '***-**-9012',
    },
    financial: {
      employmentType: 'SALARIED',
      employerName: 'Austin Tech Labs',
      jobTitle: 'Junior Developer',
      yearsEmployed: 1.2,
      grossMonthlyIncome: 5200,
      existingMonthlyDebt: 950,
      housingExpense: 1400,
      creditScoreDeclared: 640,
    },
    documents: [
      {
        id: 'doc-010',
        applicationId: 'app-004',
        documentType: 'Government Photo ID',
        originalFilename: 'TX_DL_JamesWilson.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 1400000,
        verificationStatus: 'VERIFIED',
        verificationRemarks: 'Valid Texas Drivers License.',
        uploadedAt: '2026-09-25T16:00:00Z',
        verifiedAt: '2026-09-26T10:00:00Z',
        verifiedByName: 'David Vance',
      },
      {
        id: 'doc-011',
        applicationId: 'app-004',
        documentType: 'W-2 / Tax Return (2025)',
        originalFilename: 'W2_Illegible_Scan.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 890000,
        verificationStatus: 'DEFICIENT',
        verificationRemarks: 'Document scan is blurry and cut off at employer tax ID. Please re-upload legible PDF.',
        uploadedAt: '2026-09-25T16:05:00Z',
        verifiedAt: '2026-09-26T10:15:00Z',
        verifiedByName: 'David Vance',
      },
    ],
    submittedAt: '2026-09-25T16:10:00Z',
    createdAt: '2026-09-25T15:30:00Z',
    updatedAt: '2026-09-26T10:15:00Z',
  },
  {
    id: 'app-005',
    referenceNumber: 'APP-2026-0105',
    applicantId: 'usr-applicant-5',
    productId: 'prod-personal',
    product: INITIAL_PRODUCTS[0],
    assignedOfficerId: 'usr-officer-1',
    assignedOfficerName: 'David Vance',
    status: 'APPROVED',
    requestedAmount: 20000,
    requestedTenorMonths: 24,
    purpose: 'Relocation & Professional Moving Expenses',
    personal: {
      fullName: 'Sarah Connor',
      email: 'sconnor@cyberdyne.org',
      phone: '+1 (555) 999-0000',
      dateOfBirth: '1985-05-12',
      residentialAddress: '1984 Industrial Rd, Los Angeles, CA 90001',
      taxIdMasked: '***-**-1984',
    },
    financial: {
      employmentType: 'SALARIED',
      employerName: 'Vanguard Security Services',
      jobTitle: 'Security Director',
      yearsEmployed: 5.0,
      grossMonthlyIncome: 8500,
      existingMonthlyDebt: 800,
      housingExpense: 1700,
      creditScoreDeclared: 780,
    },
    documents: [],
    decision: {
      id: 'dec-001',
      applicationId: 'app-005',
      decision: 'APPROVED',
      approvedAmount: 20000,
      approvedApr: 9.95,
      approvedTenorMonths: 24,
      conditions: 'Direct payroll deduction setup and initial direct debit mandate confirmation.',
      underwriterNotes: 'Strong credit profile, DTI under 22%, spotless payment history.',
      decidedByName: 'Katherine Reed',
      decidedAt: '2026-09-24T16:30:00Z',
    },
    submittedAt: '2026-09-23T11:00:00Z',
    createdAt: '2026-09-23T10:00:00Z',
    updatedAt: '2026-09-24T16:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    applicationId: 'app-001',
    actorId: 'usr-officer-1',
    actorName: 'David Vance',
    actorRole: 'LOAN_OFFICER',
    eventType: 'DOCUMENT_VERIFIED',
    beforeState: 'PENDING',
    afterState: 'VERIFIED',
    notes: 'Verified US Passport for Alex Taylor',
    timestamp: '2026-09-25T09:30:00Z',
  },
  {
    id: 'log-002',
    applicationId: 'app-001',
    actorId: 'usr-officer-1',
    actorName: 'David Vance',
    actorRole: 'LOAN_OFFICER',
    eventType: 'DOCUMENT_VERIFIED',
    beforeState: 'PENDING',
    afterState: 'VERIFIED',
    notes: 'Verified 2025 W-2 income proof from Apex Industrial Holdings',
    timestamp: '2026-09-25T09:35:00Z',
  },
  {
    id: 'log-003',
    applicationId: 'app-002',
    actorId: 'usr-officer-1',
    actorName: 'David Vance',
    actorRole: 'LOAN_OFFICER',
    eventType: 'STATE_TRANSITION',
    beforeState: 'UNDER_REVIEW',
    afterState: 'DOCUMENTS_VERIFIED',
    notes: 'All mandatory loan product documents validated. Forwarding to Underwriting queue.',
    timestamp: '2026-09-23T11:20:00Z',
  },
  {
    id: 'log-004',
    applicationId: 'app-005',
    actorId: 'usr-analyst-1',
    actorName: 'Katherine Reed',
    actorRole: 'RISK_ANALYST',
    eventType: 'DECISION_RECORDED',
    beforeState: 'RISK_ASSESSED',
    afterState: 'APPROVED',
    notes: 'Approved ₹20,000 at 9.95% APR for 24 months. Notice of Sanction issued.',
    timestamp: '2026-09-24T16:30:00Z',
  },
];
